spring:
  application:
    name: movie
  profiles:
    active: stage1
  rabbitmq:
    addresses: 10.20.9.92:5673, 10.20.9.92:5674, 10.20.9.92:5672
    username: ticket
    password: 123456
    virtual-host: /ticket

#log
logging:
  config: classpath:log4j2.xml

#RestTemplate
rest:
  read :
    timeout: 5000
  connect :
    timeout: 15000
user:
  serviceUrl: http://zuul/user/

eureka:
#  instance:
#    lease-renewal-interval-in-seconds: 租期更新时间，默认30s
#    lease-expiration-duration-in-seconds: 租期到期时间，默认90s
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://stage1:9000/eureka/,http://stage2:9001/eureka/

---
spring:
  profiles: stage1
server:
  port: 8010
---
spring:
  profiles: stage2
server:
  port: 8020