spring:
  application:
    name: movie

server:
  port: 8010

#log
logging:
  config: classpath:log4j2.xml

#RestTemplate
rest:
  read :
    timeout: 5000
  connect :
    timeout: 15000
user:
  serviceUrl: http://user/

eureka:
#  instance:
#    lease-renewal-interval-in-seconds: 租期更新时间，默认30s
#    lease-expiration-duration-in-seconds: 租期到期时间，默认90s
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://stage1:9000/eureka/,http://stage2:9001/eureka/
