spring:
  application:
    name: eureka
  profiles:
    active: stage1
#log
logging:
  config: classpath:log4j2.xml

---
spring:
  profiles: stage1
server:
  port: 9000
eureka:
  server:
    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 清理时间默认60 * 1000s
  instance:
    prefer-ip-address: true
    hostname: stage1
  client:
    serviceUrl:
      defaultZone: http://stage2:9001/eureka/

---
spring:
  profiles: stage2
server:
  port: 9001
eureka:
  server:
    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 清理时间默认60 * 1000s
  instance:
    prefer-ip-address: true
    hostname: stage2
  client:
    serviceUrl:
      defaultZone: http://stage1:9000/eureka/